spring:
  application:
    name: credit-application-system
  datasource:
    url: jdbc:h2:mem:credit_application_system_db
    username: jrpbjr
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
      web-allow-others: false
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
springdoc:
  swagger-ui:
    path: /swagger-ui.html