spring:
  application:
    name: credit-application-system
  datasource:
    url: jdbc:h2:mem:credit_application_system_db
    username: jrpbjr
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      propeties:
        hibernat.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
      web-allow-others: false